config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "dashboard#index"
  resources :customers, only: [ :index ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/customer_search_term.rb
class CustomerSearchTerm
attr_reader :where_clause, :where_args, :order 

def initialize(search_term)
  search_term = search_term.downcase 
  @where_clause = ""
  @where_args = {}
  if search_term =~ /@/
    build_for_email_search(search_term)
  else
    build_for_name_search(search_term)
  end 
end

  private

    def build_for_name_search(search_term)
      @where_clause << case_insensitive_search(:first_name) 
      @where_args[:first_name] = starts_with(search_term)
      @where_clause << " OR #{case_insensitive_search(:last_name)}" 
      @where_args[:last_name] = starts_with(search_term)
      @order = "last_name asc" 
    end

    def starts_with(search_term) search_term + "%"
    end

    def case_insensitive_search(field_name) "lower(#{field_name}) like :#{field_name}"
    end

    def extract_name(email) email.gsub(/@.*$/,'').gsub(/[0-9]+/,'')
    end

    def build_for_email_search(search_term)
      @where_clause << case_insensitive_search(:first_name) 
      @where_args[:first_name] = starts_with(extract_name(search_term))
      @where_clause << " OR #{case_insensitive_search(:last_name)}" 
      @where_args[:last_name] = starts_with(extract_name(search_term))
      @where_clause << " OR #{case_insensitive_search(:email)}" 
      @where_args[:email] = search_term
      @order = "lower(email) = " + 
        ActiveRecord::Base.connection.quote(search_term) + 
        " desc, last_name asc"
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController 
  PAGE_SIZE = 10

  def index

    @page = (params[:page] || 0).to_i

    if params[:keywords].present?
      @keywords = params[:keywords]
      customer_search_term = CustomerSearchTerm.new(@keywords) 
      @customers = Customer.where(
        customer_search_term.where_clause,
        customer_search_term.where_args).
        order(customer_search_term.order).
        offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
    else
      @customers = []
    end
    respond_to do |format|
      format.html {}
      format.json {
        render json: { customers: @customers }
      }
    end
  end 
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_pager.html.erb
<nav>
  <ul class="pager">
    <% if page > 0 %>
      <li class="previous">
        <%= link_to "&larr; Previous".html_safe, customers_path(keywords: keywords, page: page - 1), title: "Previous Page" %>
      </li>
    <% end %>
    <li class="next">
      <%= link_to "Next &rarr;".html_safe, customers_path(keywords: keywords, page: page + 1), title: "Next Page" %>
    </li> </ul>
</nav>

app/views/customers/index.html.erb
<section>
  <shine-customer-search></shine-customer-search>
</section>
<%= javascript_pack_tag "customers" %>

app/views/dashboard/index.html.erb
<header>
  <h1>
    Welcome to Shine, <%= current_user.email %>
  </h1>
  <h2>
    We're using Rails <%= Rails.version %>
  </h2>
</header>
<section>
  <p>
    Future home of Shine's Dashboard
  </p>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag "application" %>
    <%= stylesheet_pack_tag "application" %>
  </head>

  <body class="container">
    <h1>Rails:<%= Rails.env %></h1>
    <% if notice.present? %>
      <aside class="alert alert-info"> 
        <%= notice %>
      </aside>
    <% end %>
    <% if alert.present? %>
      <aside class="alert alert-danger"> 
        <%= alert %>
      </aside>
    <% end %>
    <%= yield %>
  </body>
</html>